## Embedded server configuration
server:
   port: 8123

## Log level configuration
logging:
   level:
      ROOT: INFO
      com.vantea: TRACE

## Multichain configuration
multichain:
   rpc:
      host: 127.0.0.1
      auth: bXVsdGljaGFpbnJwYzpFRHd1NFZialRHS0V0RDYyQXRUaHJuU2p3akZtaHo0UllrM3NLVWZxYXBHSw==
      port: 55557
      baseurl: http://127.0.0.1:55557
      adminAddress: 128v3VGKPxasH1FSgBo6ChqC1Y6mhKM38e
      nodePingTimeoutMs: 500 
      
## Security configuration
spring:
   security:
      user:
         name: wrapper
         password: password



